#!/usr/bin/env bash
set -euo pipefail
# Reset the lab: remove runtime artifacts, PCAP, generated logs, received payloads,
# temporary QR files, and temporary keys without destroying base challenge source files.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "[*] Resetting Six Ways Out lab artifacts..."

# Remove runtime directory (received payloads, PIDs, logs)
if [[ -d "$ROOT/runtime" ]]; then
    rm -rf "$ROOT/runtime"
    echo "[+] Removed runtime/"
fi

# Remove output directory (PCAP, Zeek logs, challenge ZIPs)
if [[ -d "$ROOT/output" ]]; then
    rm -rf "$ROOT/output"
    echo "[+] Removed output/"
fi

# Remove temporary attack artifacts on victim
for d in /tmp/.u1 /tmp/.u2 /tmp/.u4 /tmp/.u5 /tmp/.u6 \
         /tmp/.k1 /tmp/.k4 /tmp/.k6 /tmp/.hex /tmp/.gz \
         /tmp/.b32 /tmp/.u6.enc /tmp/note /tmp/.u1.xor \
         /tmp/.u1.b64 /tmp/legit.log.gz /tmp/legit.log.b64; do
    rm -f "$d" 2>/dev/null || true
done

# Remove FTP uploads
if [[ -d /srv/ftp/exfil ]]; then
    rm -rf /srv/ftp/exfil/*
    echo "[+] Cleared FTP uploads"
fi

# Remove received payloads on services VM
for d in /var/mail /var/spool/mail; do
    find "$d" -type f -exec rm -f {} \; 2>/dev/null || true
done

# Clear audit log (will be regenerated on next run)
if [[ -f /var/log/audit/audit.log ]]; then
    : > /var/log/audit/audit.log 2>/dev/null || true
fi

# Clear bash history
if [[ -f /root/.bash_history ]]; then
    : > /root/.bash_history 2>/dev/null || true
fi

# Remove generated XLSX (will be regenerated by setup_victim.sh)
if [[ -f /opt/finance/q3_forecast.xlsx ]]; then
    rm -f /opt/finance/q3_forecast.xlsx
    echo "[+] Removed generated XLSX"
fi

echo "[+] Lab reset complete. Run setup scripts again to regenerate."